### ISSUE TITLE
[Datepicker] Missing hover events on month and year selection

### ISSUE THREAD

**Issue by fabriciosw** [FilipePfluck/PlucoUI#8]
**Issue Overview**
The current implementation of the datepicker lacks hover events functionality when selecting months and years. This absence of hover events impacts the user experience by providing limited visual feedback during the selection process, particularly when navigating through months and years.

**Expected Behavior**
Ideally, when users hover over month and year selectors within the datepicker, there should be visual cues indicating the selection, such as highlighting or changing color, to provide clarity and improve usability.

**Current Behavior**
Currently, there are no hover events implemented for month and year selection. As a result, users are unable to visually confirm their intended selections before clicking, leading to potential confusion and frustration.

**Proposed Solution**
Integrate hover events for month and year selectors within the datepicker interface. When users hover over these elements, implement visual feedback to indicate the current selection, enhancing the user experience and improving usability.

**Steps to Reproduce**
Open the datepicker interface.
Click on month/year selection.
Attempt to hover over the month and year selectors.
Notice the absence of any visual feedback or indication of the current selection upon hover.

**Comment by FilipePfluck** [comment]
Thanks for taking your time creating this issue. I'll take a look into this

**Comment by fabriciosw** [comment]
Great to hear! Anxious to see progress on this issue.
